Squashed commit of the following:
commit 0abd0980c8a9689c821310c879ef6a447299155d
Author: shufengw <imgamer@163.com>
Date:   Wed Feb 22 09:52:01 2017 +0800

    调整工程文件来源：使用../../server/codes/dbx中的文件，保持开发同步。

commit d7987a6cebece48627b5786342ea2ae9f839df75
Merge: fb97185 477d676
Author: mandarin14 <gjx14@sina.cn>
Date:   Wed Feb 22 09:38:05 2017 +0800

    Merge branch 'master' of https://bitbucket.org/imgamer/dbx

commit 477d67630def2487363f1fd04e0cf9a262333018
Author: shufengw <imgamer@163.com>
Date:   Tue Feb 21 16:40:14 2017 +0800

    修正：DBIssue.h:66: error: candidate is: virtual bool DBIssueCallSQL::OnProgress()

commit 2310d087616c819a1ffa44ae4d7b8fbe6782cce9
Author: shufengw <imgamer@163.com>
Date:   Tue Feb 21 16:36:46 2017 +0800

    修正一些协议合并时导致的错误

commit 077df057c0c9885283d32b7a1753c4c76eb9fc63
Author: shufengw <imgamer@163.com>
Date:   Tue Feb 21 16:05:36 2017 +0800

    update

commit 7fd0ba88ef92a596ef403194384093c2a340d50c
Author: shufengw <imgamer@163.com>
Date:   Tue Feb 21 16:01:35 2017 +0800

    修正memcpy的使用bug，消除编译警告。